### ISSUE TITLE
[BUG] Could not pip install feathr - deltalake error

### ISSUE THREAD

**Issue by daxsorbito** [feathr-ai/feathr#687]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the Feathr community.

### Feathr version

latest

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 20.0)**: MacOS Monterey
- **Python version**: Python 3.10.5

### Describe the problem

Doing a `pip install feathr` would yield me an error. It would not proceed because it could not build the wheel for the deltalake package.

Below is the log:
```
Collecting deltalake
  Using cached deltalake-0.6.1.tar.gz (4.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 341, in run
...
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 89, in _build_backend
    obj = import_module(mod_path)
  File "/usr/local/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'maturin'
```

### Code to reproduce bug

```bash
pip3 install feathr
```

### What component(s) does this bug affect?

- [X] `Python Client`: This is the client users use to interact with most of our API. Mostly written in Python.
- [ ] `Computation Engine`: The computation engine that execute the actual feature join and generation work. Mostly in Scala and Spark.
- [ ] `Feature Registry API`: The frontend API layer supports SQL, Purview(Atlas) as storage. The API layer is in Python(FAST API)
- [ ] `Feature Registry Web UI`: The Web UI for feature registry. Written in React

**Comment by blrchen** [comment]
I am not able to reproduce this on my MaC but I do hear @ahlag reported a similar issue, @ahlag is this the same issue you experienced? Do you mind share how you resolve the deltalake pip install issue?

**Comment by daxsorbito** [comment]
The workaround for me right now is to set the version of deltalake to `0.5.8`. in the `setup.py` and did a local folder pip install.

**Comment by ahlag** [comment]
@blrchen @daxsorbito 

I had the same issue. The workaround for me is the same. I had also raised an issue to the DeltaLake Team about this issue. (Please refer below) Therefore, I do not think this is an issue on Feathr’s side.
https://github.com/delta-io/delta-rs/issues/808#issuecomment-1247784046

**Comment by daxsorbito** [comment]
Could we lock the version of deltalake?

**Comment by xiaoyongzhu** [comment]
@daxsorbito @ahlag thanks for this issue, I also got this reported from other users. Will lock the delta lake version.
